paradise-fi/RoFI

RoFILib/configuration/Generators.cpp, RoFILib/configuration/Generators.h
Implemented bisimpleNext, may be better than simpleNext for astar-like algorithms
=> RoFILib: Implement bisimple next

RoFILib/configuration/Configuration.cpp, RoFILib/reconfig/test/test.cpp
I hope the test I added explains what caused the bug.
=> RoFILib: Fix bug where not connected confs were considered connected

RoFISim/hal/rofi_hal.hpp, doc/Makefile, doc/conf.py, doc/index.rst, doc/rofisim/index.rst, doc/rofisim/rofihal.rst
Add RoFISim folder to docs.
Document HAL in RoFISim.
=> RoFISim: Add docs

data/gazebo/models/universalModule/model.sdf, data/gazebo/worlds/two_modules.world, tools/gazebosimTools/worldCreator/worldCreator.cpp, tools/gazebosimTools/worldCreator/worldCreator.hpp
Adds active holding of position for worlds created from configuration by world creator
=> tools: Add holding position into world creator

setup.sh
=> releng: Add more check to setup.sh

setup.sh
- Fix warning in setup.sh
- Fix locating gazebo setup script
=> releng: setup.sh fixes

doc/intro/compiling.rst, doc/intro/structure.rst
=> doc: Update compilation info

doc/intro/suites/desktop.rst, softwareComponents/gazebosim/common/CMakeLists.txt, softwareComponents/gazebosim/distributor/CMakeLists.txt, softwareComponents/gazebosim/rofiModule/CMakeLists.txt, softwareComponents/gazebosim/roficom/CMakeLists.txt, softwareComponents/rofiHalSim/CMakeLists.txt, softwareComponents/simplesim/gazebo_master/CMakeLists.txt, softwareComponents/simplesim/rofi_interface/CMakeLists.txt, suites/desktop/CMakeLists.txt, tools/gazebosimTools/CMakeLists.txt, tools/gazebosimTools/worldCreator/CMakeLists.txt
=> rofisim: Compiling without gazebo

.github/workflows/build.yml, releng/tools/_rmake.completion.py, releng/tools/rmake, softwareComponents/atoms/include/atoms/containers.hpp, softwareComponents/atoms/include/atoms/patterns.hpp, softwareComponents/configuration/rofibot.cpp, softwareComponents/configuration/test/rofibot.cpp, softwareComponents/configuration/universalModule.cpp
- Fixes broken test in configuration
- Runs the tests with github-ci on both Release and Debug mode
- Unifies the test target names, so that all tests are run with the `rmake --test --all` command
=> Run and fix tests

softwareComponents/configuration/include/configuration/rofibot.hpp
Please review; the fix is pretty straightforward. Related to #101.
=> configuration: Fix Modules' positions cleanup bug

softwareComponents/configuration/include/configuration/pad.hpp, softwareComponents/configuration/include/configuration/rofibot.hpp, softwareComponents/configuration/include/configuration/serialization.hpp, softwareComponents/configuration/src/joints.cpp, softwareComponents/configuration/src/rofibot.cpp, softwareComponents/configuration/src/universalModule.cpp, softwareComponents/configuration/test/rofibot.cpp, softwareComponents/configuration/test/serialization.cpp, softwareComponents/simplesimClientLib/include/simplesim_client.hpp, softwareComponents/simplesimClientLib/src/simplesim_client.cpp, softwareComponents/simplesimLib/include/simplesim/module_states.hpp, tools/rofiTool/build.cpp, tools/rofiTool/build.hpp, tools/rofiTool/check.cpp, tools/rofiTool/check.hpp, tools/rofiTool/preview.cpp, tools/rofiTool/preview.hpp, tools/rofiTool/rendering.cpp, tools/simplesim/main.cpp, tools/simplesimClient/main.cpp, tools/simplesimServer/main.cpp
Mainly add an initial support for attributes.
=> Configuration

.github/workflows/build.yml, Dockerfile, softwareComponents/stm32cxx/src/system/system.cpp
Solves:
- #145 
- add missing CI check for firmware
=> releng: Introduce single CI image

softwareComponents/simplesimLib/include/simplesim/command_handler.hpp, softwareComponents/simplesimLib/include/simplesim/inner_state.hpp, softwareComponents/simplesimLib/include/simplesim/module_states.hpp, softwareComponents/simplesimLib/src/command_handler.cpp, softwareComponents/simplesimLib/src/module_states.cpp
=> simplesim: Add connector and joint structs

softwareComponents/configuration/include/configuration/rofibot.hpp, softwareComponents/configuration/test/joints.cpp, softwareComponents/configuration/test/rofibot.cpp, softwareComponents/configuration/test/serialization.cpp
=> Return exact module type

doc/rofilib/configuration.rst, softwareComponents/configuration/include/configuration/rofibot.hpp, softwareComponents/configuration/json_include/configuration/serialization.hpp, softwareComponents/configuration/test/serialization.cpp, tutorials/simulator/task_1_solution/configuration.json, tutorials/simulator/task_4_solution/configuration.json, tutorials/simulator/task_6_solution/configuration.json
* add docs
* flatten module representation in json
* move helper functions to inner `details` namespace
=> Configuration: Add docs + tweak serialization

Dockerfile, doc/intro/suites/desktop.rst, releng/cmake/RustTests.cmake, releng/tools/_extract_rust_executable.py, softwareComponents/rust-rofi_voxel/.gitignore, softwareComponents/rust-rofi_voxel/CMakeLists.txt, softwareComponents/rust-rofi_voxel/Cargo.toml, softwareComponents/rust-rofi_voxel/src/lib.rs, suites/desktop/CMakeLists.txt
Tools for integration Rust into RoFI ecosystem
=> Rust in cmake

softwareComponents/configuration/json_include/configuration/serialization.hpp, softwareComponents/configuration/src/rofiworld.cpp, softwareComponents/configuration/src/universalModule.cpp, softwareComponents/configuration/test/serialization.cpp, softwareComponents/networking/include/physical_netif.hpp, softwareComponents/networking/include/roif.hpp
=> Fix wrong uses of ROFI_UNREACHABLE

doc/intro/suites/desktop.rst
Add a mention of CLP library to the getting started guide.
=> doc: Add missing dependecy

Dockerfile, experiments/voxel/full_traversal.Dockerfile, experiments/voxel/utils.py, experiments/voxel/visualize_state_graph.py, softwareComponents/voxelReconfig/src/atoms/rotation.rs, softwareComponents/voxelReconfig/src/connectivity/graph.rs, softwareComponents/voxelReconfig/src/counters.rs, softwareComponents/voxelReconfig/src/lib.rs, softwareComponents/voxelReconfig/src/reconfig/algs/astar/mod.rs, softwareComponents/voxelReconfig/src/reconfig/algs/astar/nopt/mod.rs, softwareComponents/voxelReconfig/src/reconfig/algs/bfs/mod.rs, softwareComponents/voxelReconfig/src/reconfig/mod.rs, softwareComponents/voxelReconfig/src/voxel/mod.rs, softwareComponents/voxelReconfig/src/voxel/opt.rs, tools/voxel/CMakeLists.txt, tools/voxel/rofi-voxel, tools/voxel/src/bin/rofi-voxel_full_traversal_bfs.rs, tools/voxel/src/bin/rofi-voxel_main.rs, tools/voxel/src/lib.rs
Adds logging by a crate to voxel.
Adds flags for specifying logging and normal (result) output.
Also adds counters to algorithms for some insight about the state graph.
=> Voxel logging

softwareComponents/voxelReconfig/Cargo.toml, tools/voxel/Cargo.toml
=> Rust RelWithDebInfo
