RoFILib/configuration/IO.h
RoFILib/distribute/DistributedReader.h

The current file format does not allow for empty spaces and comments. This makes the hand-writing of larger configurations challenging.
This pull request allows empty lines to structure the content and also allows for bash-like comments - a line starting with `#` is ignored.

Improve the configuration file format

---

RoFILib/configuration/Configuration.cpp
RoFILib/configuration/Configuration.h
RoFILib/util/CMakeLists.txt
RoFILib/util/emptyDockFill.cpp

New utility. Given path to configuration (`config`) a path to directory (`dir`), fills `dir` with all configurations that they have `config` as subconfig, but they have one more module.

RoFILib: Implement emptyDockFill

---

RoFILib/CMakeLists.txt
RoFILib/snake_reconfig/CMakeLists.txt

This PR targets #20. It adds basic options to configure the RoFILib build - especially the options to remove heavy GUI dependencies which allow for compiling for a headless environment.

Add basic options to configure build

---

RoFILib/configuration/Configuration.cpp
RoFILib/configuration/Configuration.h

Ive realised that I make no difference between cross and forward edges, so my logic about local fixing spanning tree was faulty.

RoFILib: Remove faulty logic fixing spanning tree

---

RoFISim/hal/gazebo_client_holder.hpp
RoFISim/hal/rofi_hal.cpp
RoFISim/hal/subscriber_wrapper.hpp
RoFISim/hal/worker.hpp

Reduces copying of `shared_ptr`. Instead uses reference where possible.

RoFISim: Reduce usage of shared pointers

---

setup.sh

Argument `-printf '%f\n'`, which is not in POSIX, was passed to `find`, causing the `setup.sh` to fail on MacOS.

releng: Replace non-POSIX argument passed to find

---

doc/intro/compiling.rst
examples/simulator/pythonInterface/oscilate.py
examples/simulator/pythonInterface/readme.md
setup.sh
softwareComponents/rofiHalSimPy/CMakeLists.txt
softwareComponents/rofiHalSimPy/hal.cpp
suites/desktop/CMakeLists.txt

Add simple Python bindings for HAL. Note that in the future, we will have to restructure the bindings once we add bindings for configuration & other algorithms. However, I would postpone the decision about the structure.

simulator: Add Python bindings for HAL

---

tools/rofiTool/check.hpp
tools/rofiTool/preview.cpp

Without this order, the command crashed with the following trace for me for some reason:
#0  0x00007fcfad22ccbf in std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*) () from /nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib/lib/libstdc++.so.6
#1  0x0000000000440153 in std::__cxx11::list<std::unique_ptr<Dim::Cli::OptBase, std::default_delete<Dim::Cli::OptBase> >, std::allocator<std::unique_ptr<Dim::Cli::OptBase, std::default_delete<Dim::Cli::OptBase> > > >::_M_insert<std::unique_ptr<Dim::Cli::OptBase, std::default_delete<Dim::Cli::OptBase> > > (__position=..., this=0x7fff58df5700)
at /nix/store/dlni53myj53kx20pi4yhm7p68lw17b07-gcc-10.3.0/include/c++/10.3.0/bits/stl_list.h:1912
#2  std::__cxx11::list<std::unique_ptr<Dim::Cli::OptBase, …

rofi-tool: fix segfault

---

softwareComponents/configuration/Configuration.cpp
softwareComponents/configuration/Configuration.h

All uses expected this to return the reference, not a new map (which resulted in some undefined behaviour).

configuration: Fix return type

---

softwareComponents/atoms/include/atoms/containers.hpp
softwareComponents/atoms/include/atoms/patterns.hpp
softwareComponents/configuration/rofibot.cpp

`ATOMS_CLONEABLE` requires an abstract base or derived class. `Module` is neither of those (so the code doesn't compile at the moment).

Minor code improvements (atoms, configuration)

---

.github/workflows/build.yml

Fixes building the docs two times (the build is the same in Release and Debug).

releng: Build docs only once in CI

---

releng/cmake/STM32Cube.cmake

Added new sublibs for uart/opamp/pwr and extra functions for rcc into the base lib

Update STM32Cube.cmake with new libs

---

Dockerfile
doc/conf.py
doc/intro/suites/doc.rst
releng/cmake/Spinx.cmake
setup.sh

Recommonmark is discontinued and recomends MyST. (Both are for parsing markdown in sphinx.)
@yaqwsx Do you think you could update the docker image? (You can install there both myst_parser and recommonmark for now.)
Taken from #177 so it can be merged quicker, since it's not critical.

Migrate to myst

---

doc/intro/suites/doc.rst

In Ubuntu, `inotify-tools` are required for `rmake --doc`. Otherwise, the command fails with `ERROR: could not find 'inotifywait'. Aborting.`

doc: Add note about inotify requirements

---

doc/rofilib/configuration.rst

Fix bad format for `moduleJoints` in docs.

doc: Fix old configuration format

---

suites/desktop/CMakeLists.txt

suites: Fix build fail on Ubuntu 22.04

---

softwareComponents/kinematics/fReconfig.hpp
suites/desktop/CMakeLists.txt

On Ubuntu 22.04 gcc 12 complains about missing header `<memory>` and build fails.

Ubuntu22.04 build fail

---

tools/gazebosimTools/worldCreator/worldCreator.cpp

On newer libc++ an exception is thrown because using `std::ws` on stream on `eof` now sets `fail` bit.

tools: Fix an exception throw on newer libc++

---

softwareComponents/atoms/include/atoms/result.hpp

Allows usage:
```cpp
auto result = // get `Result`
if ( !result ) {
return result.assume_error_result();
// OR if copying error_type is expensive
return std::move( result ).assume_error_result();
}
// use `*result`
```
This could be done before by using
```cpp
return atoms::result_error( result.assume_error() );
```
but using `assume_error_result` is visually cleaner (i.e. the result from which the error is returned is at the beginning).

atoms: Add assume_error_result to Result

---

tools/rofiTool/CMakeLists.txt
tools/rofiTool/build.cpp
tools/rofiTool/build.hpp
tools/rofiTool/check.cpp
tools/rofiTool/check.hpp
tools/rofiTool/commands.cpp
tools/rofiTool/commands.hpp
tools/rofiTool/main.cpp
tools/rofiTool/points.cpp
tools/rofiTool/points.hpp
tools/rofiTool/preview.cpp
tools/rofiTool/preview.hpp

Provides the ability to use commands check, points and preview from rofi-tool on configurations in the JSON format (file with .json extension); contained in the first commit.
Second commit is a suggestion to merge headers and extract the common functionality of these commands into auxiliary functions.

rofi-tool: Parse configuration from JSON

---

softwareComponents/configuration/include/configuration/joints.hpp
softwareComponents/configuration/include/configuration/rofiworld.hpp
softwareComponents/configuration/src/rofiworld.cpp
softwareComponents/configuration/test/joints.cpp
softwareComponents/configuration/test/serialization.cpp

First commit: Adds boundary checking for parameters given to setPositions function (boundaries are defined by joint limits), which sets the parameters (rotations and/or other) of a joint; if values are out of bounds, throws logic_error.
Also adds changePositionsBy function, which does not set the parameters to given values, but adds their values to the values given. If the resulting values are out of bounds, does not throw an error, but returns an atoms::result_error, and does not change the current parameters of the joint.
Second commit: Changes tests to reflect the functionality introduced by the first commit.

configuration: Check joint limits when setting joint positions

---

.github/workflows/build.yml
doc/index.rst
doc/releng/index.rst
releng/tools/updateDockerImages

This PR addresses two problems:
- there has been a problem with incorrect working directory permission in GH runners. It wasn't noticeable until Git fixed a security bug (https://github.com/actions/runner-images/issues/6775)
- the checkout and other actions use Node JS. The versions were bumped, as Node 14 was deprecated in GH actions.

Fix recent CI problems

---

softwareComponents/configuration/include/configuration/rofiworld.hpp

Does not assume modules are sorted by their ID.
SimpleCollision now checks if positions occupied by modules are within distance of 1, instead of checking if the positions are the same (does not matter for 90 degrees of rotation, but rofiworld below is valid according to the old check).
RofiWorld that was valid before fix:
C
M 2 90 0 180
M 1 90 45 0
M 0 90 90 0
E 1 A -Z S -Z A 2
E 0 A -Z S -Z B 1

Fix configuration validity check using SimpleCollision

---

softwareComponents/isoreconfig/include/isoreconfig/geometry.hpp
softwareComponents/isoreconfig/include/isoreconfig/isomorphic.hpp
softwareComponents/isoreconfig/src/geometry.cpp
softwareComponents/isoreconfig/src/isomorphic.cpp
tools/rofiTool/CMakeLists.txt
tools/rofiTool/rendering.cpp
tools/rofiTool/shape.cpp

Adds "shape" command to rofi-tool, which takes two RofiWorlds and decides whether their physical shape (defined using standard module decomposition - a point for each RoFICom and each connection) is equal or not .

rofiTool: add shape command

---

examples/simulator/basicJointForce/basicJointForce.cpp
examples/simulator/basicJointPosition/basicJointPosition.cpp
examples/simulator/basicJointVelocity/basicJointVelocity.cpp
examples/simulator/basicMove/basicMove.cpp
softwareComponents/rofiHalEsp32/src/rofi_hal.cpp
softwareComponents/rofiHalInc/include/rofi_hal.hpp
softwareComponents/rofiHalSim/rofi_hal.cpp
softwareComponents/rofiHalSimPy/hal.cpp
tutorials/simulator/task_3_solution/module_code.cpp
tutorials/simulator/task_4_solution/module_code.cpp
tutorials/simulator/task_5_solution/module_code.cpp
tutorials/simulator/task_6_solution/module_code.cpp

This PR
* adds a new non-blocking variant for `wait` function – `delay`;
* implements `wait` and `delay` for esp32;
* fixes non-blocking `wait` behaviour in the SimpleSim (You can check the behaviour using tutorial 2 by adding `wait`/`delay` before the Hello, World!).

Add hal::delay function, implement delay/wait for esp32

---

releng/tools/rmake

Adds the -j switch to the rmake command, which specifies the maximum number of threads to use during compilation of targets.

rmake: specify max threads using -j

---

softwareComponents/messageLogger/include/message_logger.hpp
softwareComponents/rofiHalSim/CMakeLists.txt
softwareComponents/rofiHalSim/message_logger.hpp
softwareComponents/rofiHalSim/publish_worker.hpp
softwareComponents/rofiHalSim/rofi_hal.cpp
softwareComponents/rofiHalSim/session_id.cpp
softwareComponents/rofiHalSim/session_id.hpp
softwareComponents/rofiHalSim/subscriber_wrapper.hpp
softwareComponents/simplesimLib/include/simplesim/distributor.hpp
softwareComponents/simplesimLib/include/simplesim/locked_module_communication.hpp
softwareComponents/simplesimLib/src/distributor.cpp
softwareComponents/simplesimLib/src/locked_module_communication.cpp

Adds logging subcribing to topics to simplesim, when using --verbose

Simplesim log subscribing
